# Generated by Django 5.0.3 on 2024-03-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=65, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('imageURL', models.URLField()),
                ('firstName', models.CharField(max_length=32)),
                ('lastName', models.CharField(max_length=64)),
                ('education', models.TextField()),
                ('occupation', models.TextField()),
                ('socialNetworks', models.TextField()),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=65, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('imageURL', models.URLField()),
                ('firstName', models.CharField(max_length=32)),
                ('lastName', models.CharField(max_length=64)),
                ('education', models.TextField()),
                ('occupation', models.TextField()),
                ('socialNetworks', models.TextField()),
                ('address', models.TextField()),
            ],
        ),
    ]
